<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\Rule;
use Illuminate\Database\Seeder;

/**
 * Seeds ALL TIMS rules per spec §7.1.
 * NO point values are hardcoded in application code — only here in seed data.
 */
class TimsRuleSeeder extends Seeder
{
    public function run(): void
    {
        $company = Company::where('code', 'TIMS')->firstOrFail();
        $id      = $company->id;

        $rules = array_merge(
            $this->kpiRules($id),
            $this->positiveRules($id),
            $this->negativeRules($id),
            $this->recoveryRules($id),
            $this->tierRules($id),
        );

        foreach ($rules as $rule) {
            Rule::updateOrCreate(
                ['company_id' => $id, 'code' => $rule['code']],
                $rule
            );
        }
    }

    private function kpiRules(int $id): array
    {
        return [
            [
                'company_id'       => $id,
                'category'         => 'kpi',
                'calculation_type' => 'range',
                'code'             => 'tims_kpi_min_calls',
                'name'             => 'Minimum 40 Connected Calls',
                'points'           => 0,
                'threshold_min'    => 40,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 40,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 1,
                'description'      => 'Executive must have at least 40 connected calls per day',
            ],
            [
                'company_id'       => $id,
                'category'         => 'kpi',
                'calculation_type' => 'range',
                'code'             => 'tims_kpi_min_meetings',
                'name'             => 'Minimum 1 Confirmed Meeting',
                'points'           => 0,
                'threshold_min'    => 1,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 1,
                'input_metric'     => 'confirmed_meetings',
                'is_active'        => true,
                'sort_order'       => 2,
                'description'      => 'Executive must have at least 1 confirmed meeting per day',
            ],
        ];
    }

    private function positiveRules(int $id): array
    {
        return [
            // ── Daily Call Activity ──────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'range',
                'code'             => 'tims_pos_calls_40_49',
                'name'             => '40–49 Connected Calls',
                'points'           => 4,
                'threshold_min'    => 40,
                'threshold_max'    => 49,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 10,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'range',
                'code'             => 'tims_pos_calls_50_64',
                'name'             => '50–64 Connected Calls',
                'points'           => 6,
                'threshold_min'    => 50,
                'threshold_max'    => 64,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 11,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'range',
                'code'             => 'tims_pos_calls_65_plus',
                'name'             => '65+ Connected Calls',
                'points'           => 8,
                'threshold_min'    => 65,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 65,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 12,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'streak',
                'code'             => 'tims_pos_call_streak_7',
                'name'             => '7 Consecutive Working Days (40+ Calls)',
                'points'           => 8,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'call_streak_7',
                'is_active'        => true,
                'sort_order'       => 13,
                'condition_json'   => ['streak_metric' => 'call_streak_7'],
            ],
            // ── Meeting Arrangement ──────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'range',
                'code'             => 'tims_pos_meeting_1',
                'name'             => '1 Confirmed Meeting',
                'points'           => 3,
                'threshold_min'    => 1,
                'threshold_max'    => 1,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'confirmed_meetings',
                'is_active'        => true,
                'sort_order'       => 20,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'range',
                'code'             => 'tims_pos_meeting_2_3',
                'name'             => '2–3 Confirmed Meetings',
                'points'           => 5,
                'threshold_min'    => 2,
                'threshold_max'    => 3,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'confirmed_meetings',
                'is_active'        => true,
                'sort_order'       => 21,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'range',
                'code'             => 'tims_pos_meeting_4_plus',
                'name'             => '4+ Confirmed Meetings',
                'points'           => 8,
                'threshold_min'    => 4,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 4,
                'input_metric'     => 'confirmed_meetings',
                'is_active'        => true,
                'sort_order'       => 22,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'streak',
                'code'             => 'tims_pos_meeting_streak_7',
                'name'             => '7-Day Meeting Consistency',
                'points'           => 10,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'meeting_streak_7',
                'is_active'        => true,
                'sort_order'       => 23,
                'condition_json'   => ['streak_metric' => 'meeting_streak_7'],
            ],
            // ── Meeting Attendance ───────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'per_unit',
                'code'             => 'tims_pos_meeting_attended',
                'name'             => 'Customer Attended Meeting',
                'points'           => 4,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'meetings_attended',
                'is_active'        => true,
                'sort_order'       => 30,
                'description'      => '+4 per attended meeting',
            ],
            // ── Lead Management ──────────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'boolean',
                'code'             => 'tims_pos_first_contact_45',
                'name'             => 'First Contact Within 45 Minutes',
                'points'           => 3,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'first_contact_within_45min',
                'is_active'        => true,
                'sort_order'       => 40,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'boolean',
                'code'             => 'tims_pos_same_day_followup',
                'name'             => '100% Same Day Follow-up',
                'points'           => 3,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'all_leads_followed_up',
                'is_active'        => true,
                'sort_order'       => 41,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'boolean',
                'code'             => 'tims_pos_crm_disposition',
                'name'             => 'Correct CRM Disposition',
                'points'           => 3,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'crm_disposition_correct',
                'is_active'        => true,
                'sort_order'       => 42,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'boolean',
                'code'             => 'tims_pos_warm_lead_converted',
                'name'             => 'Warm Lead Converted',
                'points'           => 8,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'warm_lead_converted',
                'is_active'        => true,
                'sort_order'       => 43,
            ],
            [
                'company_id'       => $id,
                'category'         => 'positive',
                'calculation_type' => 'boolean',
                'code'             => 'tims_pos_cold_lead_reactivated',
                'name'             => 'Freeze/Cold Lead Reactivated',
                'points'           => 10,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'cold_lead_reactivated',
                'is_active'        => true,
                'sort_order'       => 44,
            ],
        ];
    }

    private function negativeRules(int $id): array
    {
        return [
            // ── Call Violations ──────────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_calls_33_39',
                'name'             => '33–39 Calls',
                'points'           => -3,
                'threshold_min'    => 33,
                'threshold_max'    => 39,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 100,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_calls_27_32',
                'name'             => '27–32 Calls',
                'points'           => -6,
                'threshold_min'    => 27,
                'threshold_max'    => 32,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 101,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_calls_15_26',
                'name'             => '15–26 Calls',
                'points'           => -10,
                'threshold_min'    => 15,
                'threshold_max'    => 26,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 102,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_calls_below_15',
                'name'             => 'Below 15 Calls',
                'points'           => -15,
                'threshold_min'    => 0,
                'threshold_max'    => 14,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 103,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_zero_calls',
                'name'             => 'Zero Connected Calls',
                'points'           => -20,
                'threshold_min'    => 0,
                'threshold_max'    => 0,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 104,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_less_60_attempts',
                'name'             => 'Less Than 60 Attempts',
                'points'           => -8,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 105,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_3_days_below_kpi',
                'name'             => '3 Consecutive Days Below KPI',
                'points'           => -15,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 106,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'call'],
            ],
            // ── Meeting Violations ───────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_zero_meetings',
                'name'             => 'Zero Meetings',
                'points'           => -6,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 110,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'meeting'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_3_days_no_meeting',
                'name'             => '3 Consecutive Days Without Meeting',
                'points'           => -15,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 111,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'meeting'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_meeting_not_logged',
                'name'             => 'Meeting Not Logged Properly',
                'points'           => -5,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 112,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'meeting'],
            ],
            // ── Lead Management Violations ───────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_no_first_contact',
                'name'             => 'No First Contact',
                'points'           => -8,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 120,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'lead'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_no_followup',
                'name'             => 'No Follow-up',
                'points'           => -8,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 121,
                'description'      => '-8 per lead',
                'action_json'      => ['create_violation' => true, 'violation_type' => 'lead'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_wrong_crm_disposition',
                'name'             => 'Wrong CRM Disposition',
                'points'           => -6,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 122,
                'description'      => '-6 per lead',
                'action_json'      => ['create_violation' => true, 'violation_type' => 'lead'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_warm_lead_freeze',
                'name'             => 'Warm Lead Marked Freeze Incorrectly',
                'points'           => -12,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 123,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'lead'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_freeze_reason_missing',
                'name'             => 'Freeze Reason Missing',
                'points'           => -6,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 124,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'lead'],
            ],
            // ── Conduct & Integrity ──────────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_false_attendance',
                'name'             => 'False Attendance Justification',
                'points'           => -20,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 130,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'conduct'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_crm_manipulation',
                'name'             => 'CRM Manipulation',
                'points'           => -40,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 131,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'conduct'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_communication_violation',
                'name'             => 'Communication Violation',
                'points'           => -12,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 132,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'conduct'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_customer_complaint',
                'name'             => 'Verified Customer Complaint',
                'points'           => -20,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 133,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'conduct'],
            ],
            // ── Team Lead Accountability ─────────────────────────────────────
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_team_calls_below_kpi',
                'name'             => 'Team Calls Below KPI',
                'points'           => -12,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 140,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'team_lead'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_team_meeting_below_kpi',
                'name'             => 'Team Meeting KPI Below Target',
                'points'           => -10,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 141,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'team_lead'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'negative',
                'calculation_type' => 'selected_violation',
                'code'             => 'tims_neg_failed_report_violation',
                'name'             => 'Failed to Report Violation',
                'points'           => -20,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 142,
                'action_json'      => ['create_violation' => true, 'violation_type' => 'team_lead'],
            ],
        ];
    }

    private function recoveryRules(int $id): array
    {
        return [
            [
                'company_id'       => $id,
                'category'         => 'recovery',
                'calculation_type' => 'range',
                'code'             => 'tims_rec_65_calls',
                'name'             => '65+ Connected Calls (Recovery)',
                'points'           => 6,
                'threshold_min'    => 65,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 65,
                'input_metric'     => 'connected_calls',
                'is_active'        => true,
                'sort_order'       => 200,
            ],
            [
                'company_id'       => $id,
                'category'         => 'recovery',
                'calculation_type' => 'range',
                'code'             => 'tims_rec_2_plus_attended',
                'name'             => '2+ Customer Attended Meetings (Recovery)',
                'points'           => 6,
                'threshold_min'    => 2,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 2,
                'input_metric'     => 'meetings_attended',
                'is_active'        => true,
                'sort_order'       => 201,
            ],
            [
                'company_id'       => $id,
                'category'         => 'recovery',
                'calculation_type' => 'boolean',
                'code'             => 'tims_rec_perfect_compliance',
                'name'             => 'Perfect Compliance Day (Recovery)',
                'points'           => 8,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'crm_disposition_correct',
                'is_active'        => true,
                'sort_order'       => 202,
                'condition_json'   => [
                    'all_true' => ['crm_disposition_correct', 'all_leads_followed_up', 'first_contact_within_45min'],
                ],
            ],
            [
                'company_id'       => $id,
                'category'         => 'recovery',
                'calculation_type' => 'streak',
                'code'             => 'tims_rec_zero_violations_week',
                'name'             => 'Zero Violations for Week (Recovery)',
                'points'           => 10,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'call_streak_7',
                'is_active'        => true,
                'sort_order'       => 203,
                'condition_json'   => ['streak_metric' => 'call_streak_7'],
            ],
            [
                'company_id'       => $id,
                'category'         => 'recovery',
                'calculation_type' => 'boolean',
                'code'             => 'tims_rec_crm_45min',
                'name'             => 'CRM Updated Within 45 Minutes (Recovery)',
                'points'           => 4,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => null,
                'input_metric'     => 'first_contact_within_45min',
                'is_active'        => true,
                'sort_order'       => 204,
            ],
            // Recovery cap rule — read by orchestration service
            [
                'company_id'       => $id,
                'category'         => 'recovery_cap',
                'calculation_type' => 'recovery_cap',
                'code'             => 'tims_rec_max_daily',
                'name'             => 'Maximum Daily Recovery',
                'points'           => 0,
                'threshold_min'    => null,
                'threshold_max'    => null,
                'operator'         => null,
                'threshold_value'  => 20,
                'input_metric'     => null,
                'is_active'        => true,
                'sort_order'       => 299,
                'description'      => 'Maximum daily recovery cap = 20 points',
            ],
        ];
    }

    private function tierRules(int $id): array
    {
        return [
            [
                'company_id'       => $id,
                'category'         => 'tier',
                'calculation_type' => 'tier_negative',
                'code'             => 'review_zone',
                'name'             => 'Review Zone',
                'points'           => 0,
                'threshold_min'    => null,
                'threshold_max'    => -1,
                'operator'         => '<',
                'threshold_value'  => 0,
                'input_metric'     => 'current_score',
                'is_active'        => true,
                'sort_order'       => 300,
                'description'      => 'Score is negative',
            ],
            [
                'company_id'       => $id,
                'category'         => 'tier',
                'calculation_type' => 'tier_range',
                'code'             => 'bronze',
                'name'             => 'Bronze',
                'points'           => 0,
                'threshold_min'    => 0,
                'threshold_max'    => 299,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'current_score',
                'is_active'        => true,
                'sort_order'       => 301,
            ],
            [
                'company_id'       => $id,
                'category'         => 'tier',
                'calculation_type' => 'tier_range',
                'code'             => 'silver',
                'name'             => 'Silver',
                'points'           => 0,
                'threshold_min'    => 300,
                'threshold_max'    => 699,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'current_score',
                'is_active'        => true,
                'sort_order'       => 302,
            ],
            [
                'company_id'       => $id,
                'category'         => 'tier',
                'calculation_type' => 'tier_range',
                'code'             => 'gold',
                'name'             => 'Gold',
                'points'           => 0,
                'threshold_min'    => 700,
                'threshold_max'    => 1199,
                'operator'         => 'between',
                'threshold_value'  => null,
                'input_metric'     => 'current_score',
                'is_active'        => true,
                'sort_order'       => 303,
            ],
            [
                'company_id'       => $id,
                'category'         => 'tier',
                'calculation_type' => 'tier_range',
                'code'             => 'platinum',
                'name'             => 'Platinum',
                'points'           => 0,
                'threshold_min'    => 1200,
                'threshold_max'    => null,
                'operator'         => '>=',
                'threshold_value'  => 1200,
                'input_metric'     => 'current_score',
                'is_active'        => true,
                'sort_order'       => 304,
            ],
        ];
    }
}
